name: virtualship-postprocessing
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - openpyxl
  - xarray
  - scipy
  - pandas
  - matplotlib
  - cartopy
  - cmocean
  - geopy
  - gsw
  - netcdf4
  - h5netcdf
  - plotly
  - pip
  # TODO: ideally rely on a stable release of Parcels v4, but for now pull from GitHub
  - pip:
      - git+https://github.com/Parcels-code/Parcels.git@main